version: "3.9"

services:
  web:
    image: counterflask:latest
    ports:
      - "5000:5000"
    networks:
      - my_network
    depends_on:
      - database
  database:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=vincent
      - POSTGRES_DB=td_1
    networks:
      - my_network
networks:
  my_network: